server:
  port: 8081

spring:
  application:
    name: eretain-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eretain_auth
    username: eretain
    password: eretain123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

eretain:
  jwt:
    secret: eRetainSecretKeyForJWTTokenGenerationMustBe256BitsLong!!
    expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
